name: 'infra preview & deploy'

on:
  push:
    branches:
      - master
    paths:
      - 10_infra/**
      - .github/workflows/**

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.2.8
  AWS_REGION: ap-northeast-1

defaults:
  run:
    shell: bash
    working-directory: '10_infra/'

jobs:
  preview:
    name: 'preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{env.TF_VERSION}}
      - name: Terraform format
        run: |
          terraform fmt -check
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_IAM_ROLE_ARN}}
      - name: Terraform init
        run: |
          terraform init -no-color
