name: 'n Slack Notify'

on:
  workflow_dispatch:

jobs:
  notify:
    name: Skack notify
    runs-on: ubuntu-latest
    steps:
      - name: Slack notify
        uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: 'C05D0TXH9PU'
          payload: |
            {
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Terraform and Github Actions sample App notify :ghost: and <https://google.com|this is a link>"
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
